### ISSUE TITLE
Chat preview before joining. 

### ISSUE THREAD

**Issue by rscmbbng** [JohnXLivingston/peertube-plugin-livechat#78] opened 2021-12-10 12:41 UTC
**Is your feature request related to a problem? Please describe.**

Currently the livechat is configured in such a way one needs to join the chat to see the message history. The live chat of twitch and youtube instead can be read without 'joining' the chatroom first. Joining the chatroom is only necessary if one wants to talk.

**Describe the solution you'd like**

Implement a configuration similar to https://chat.modernxmpp.org/, where the chat history is visible before joining the chat.

**Comment by JohnXLivingston** [comment] 2021-12-10 14:30
Thanks for the report. This is already on my todo list. For now, I did not manage to use this ConverseJS option. It seems that the ConverseJS version I'm using is broken.

**Comment by rscmbbng** [comment] 2021-12-10 15:41
Great! Thanks for your work.

It is this particular config option: https://conversejs.org/docs/html/configuration.html#muc-show-logs-before-join

Probably also a good idea to limit the amount of messages that gets returned to 5 or 10 last

**Comment by JohnXLivingston** [comment] 2021-12-11 10:53
> It is this particular config option: https://conversejs.org/docs/html/configuration.html#muc-show-logs-before-join

Yes I know this option. But it does not work as expected. It loads the room history, but the user don't join the room. As a result, you can see what was said before you opened the chat... but you won't receive any new message.
That's why I'd rather like to make the user join with a random nick, and propose to change it (see https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/15)



> Probably also a good idea to limit the amount of messages that gets returned to 5 or 10 last

It is actually possible to change this behavior room by room:

- as room owner, open the room in full screen
- open the top right menu
- click on the «configure button» (in french it is «configurer», I'm not sure about the english label)
- at the bottom of the form you can change these values:

![image](https://user-images.githubusercontent.com/38844060/145673904-5b325286-d3b4-431f-8477-916159e37149.png)

I could add a settings to choose these defaults values server wide.

**Comment by jcbrand** [comment] 2021-12-11 20:19
> As a result, you can see what was said before you opened the chat... but you won't receive any new message.

This is the expected behavior. Per the XMPP MUC spec, you can't get new messages without joining.

**Comment by JohnXLivingston** [comment] 2021-12-11 20:22
> > As a result, you can see what was said before you opened the chat... but you won't receive any new message.
> 
> This is the expected behavior. Per the XMPP MUC spec, you can't get new messages without joining.

Yes I know. That's why I prefer a solution like the one described in https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/15 (connect with a random nickname, and offer to change it afterwards).

**Comment by jcbrand** [comment] 2021-12-11 20:24
Ok, I'm just mentioning because you said your version of Converse is broken and I thought you might be thinking this is a bug.

**Comment by JohnXLivingston** [comment] 2021-12-11 20:27
> Ok, I'm just mentioning because you said your version of Converse is broken and I thought you might be thinking this is a bug.

Thanks! I thought it was broken, but between my 2 messages I checked the notes I have taken. Indeed, ConverseJS is working fine, but XMPP is limiting the feature.

**Comment by JohnXLivingston** [comment] 2022-04-11 16:19
I forgot to close this issue. The feature is available since version 5.4.0.

**Closed by JohnXLivingston** 2022-04-11 16:19 UTC
