### ISSUE TITLE
ConverseJS: issue connecting with YunoHost and Metronome

### ISSUE THREAD

**Issue by csolisr** [JohnXLivingston/peertube-plugin-livechat#50] opened 2021-06-17 14:46 UTC
**Describe the bug**
When attempting to connect the Livechat plugin to an existing server using YunoHost, the connection currently fails. This might be caused because YunoHost uses Metronome as its XMPP engine instead of Prosody.

**To Reproduce**
1. [Install YunoHost](https://yunohost.org/) (assuming a base URL of `https://www.example.net`)
2. As the BOSH URI is not exposed directly by YunoHost, install the Redirect app with the following settings:
    - Domain: `example.net`
    - Path to install: `/http-bind`
    - Redirect destination path: http://localhost:5290/http-bind
    - Redirect type: "Proxy, invisible (nginx proxy_pass). Everybody will be able to access it."
3. Install Peertube (assuming a subdomain of `https://peertube.example.net` for the case below)
4. Install the Livechat plugin
5. Configure the plugin to use the Metronome server bundled by YunoHost with the following settings:
    - XMPP service server: `example.net`
    - XMPP room template: `public_{{VIDEO_UUID}}@muc.example.net` (the `muc` prefix is automatically generated by YunoHost)
    - BOSH URI: `http://example.net/http-bind`
5. The following error appears when launching the diagnosis tool at `https://peertube.example.net/plugins/livechat/2.3.1/router/settings/diagnostic`:
```
{"error":"Token is invalid.","code":"invalid_request"}
```

**Expected behavior**
The diagnosis tool should detect the existing Metronome XMPP server and use it as the default.

**Desktop (please complete the following information):**
 - OS: Windows 10 on desktop, Debian Stable on server
 - Browser: Tested on Firefox, but as it's a server-side issue, it should happen in all browsers
 - Version: Tested on Firefox 89

**Additional context**
YunoHost has a hard dependency on Metronome, so attempting to install Prosody instead requires deleting YunoHost and all the apps it currently handles.

**Comment by csolisr** [comment] 2021-06-17 14:55
Further digging in I found something in the logs:
```
warn: Cannot authenticate. {
"err": {
  "statusCode": 400,
  "status": 400,
  "code": 400,
  "message": "Invalid request: malformed authorization header",
  "name": "invalid_request",
  "stack": "invalid_request: Invalid request: malformed authorization header\n
               at new InvalidRequest (/var/www/peertube/node_modules/oauth2-server/lib/errors/invalid-request-error.js:26:14)\n
               at AuthenticateHandler.getTokenFromRequestHeader (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:146:11)\n
               at AuthenticateHandler.getTokenFromRequest (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:121:17)\n
               at AuthenticateHandler.<anonymous> (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:68:19)\n
               at AuthenticateHandler.tryCatcher (/var/www/peertube/node_modules/bluebird/js/release/util.js:16:23)\n
               at Promise._settlePromiseFromHandler (/var/www/peertube/node_modules/bluebird/js/release/promise.js:547:31)\n
               at Promise._settlePromise (/var/www/peertube/node_modules/bluebird/js/release/promise.js:604:18)\n
               at Promise._settlePromiseCtx (/var/www/peertube/node_modules/bluebird/js/release/promise.js:641:10)\n
               at _drainQueueStep (/var/www/peertube/node_modules/bluebird/js/release/async.js:97:12)\n
               at _drainQueue (/var/www/peertube/node_modules/bluebird/js/release/async.js:86:9)\n
               at Async._drainQueues (/var/www/peertube/node_modules/bluebird/js/release/async.js:102:5)\n
               at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/node_modules/bluebird/js/release/async.js:15:14)\n
               at processImmediate (internal/timers.js:462:21)"
  }
}
```

**Comment by JohnXLivingston** [comment] 2021-06-17 15:50
Hello,
I think the problem is just that you are not authenticated for the diagnostic tool.
This is something i did not document (my bad): when you are on the diagnostic page, I use the Peertube oauth token that is in the browser localStorage. But I don't renew it when it is expired.
You have to open a browser window on your instance, make sure that you are logged in (as an admin), then go back to the diagnostic tool and refresh the page.

Concerning Yunohost, the plugin compatibility is on my todo list. I haven't the time to try yunohost for now. Thanks for pointing the Metronome dependency.
As Yunohost is based on debian, you should be able to install Prosody, then disable the service, as in my documentation: 
```bash
sudo apt-get install prosody;
sudo systemctl disable prosody && sudo systemctl stop prosody
```
https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/prosody.md
The installation will raise an error, as the 5280 port is already in use by Metronome. But if you disable Prosody afterward, it should not be a problem.

**Comment by JohnXLivingston** [comment] 2021-06-17 15:51
Oh, Metronome is a fork of Prosody! I did not know. Hum...

**Comment by JohnXLivingston** [comment] 2021-06-17 16:17
To install Prosody without running it (and without broking Metronome), you could try the solution given here: https://askubuntu.com/questions/779554/how-to-install-apt-package-without-starting-systemd-process
```bash
apt-get download prosody
sudo dpkg --unpack prosody.deb
```

**Comment by JohnXLivingston** [comment] 2021-06-17 16:19
To install Prosody without running it (and without broking Metronome), you could try the solution given here: https://askubuntu.com/questions/779554/how-to-install-apt-package-without-starting-systemd-process
```bash
apt-get download prosody
sudo dpkg --unpack prosody.deb
```

**Comment by mwild1** [comment] 2021-06-17 16:23
> Oh, Metronome is a fork of Prosody! I did not know. Hum...

For the record, Metronome forked from Prosody a long time ago (at least 8 years ago I think!). They may have some similarities in architecture still, but don't assume that plugins from one will work in the other (the internal APIs are different).

**Comment by JohnXLivingston** [comment] 2021-06-17 16:24
> > Oh, Metronome is a fork of Prosody! I did not know. Hum...
> 
> For the record, Metronome forked from Prosody a long time ago (at least 8 years ago I think!). They may have some similarities in architecture still, but don't assume that plugins from one will work in the other (the internal APIs are different).

Yes, I just saw that. Thanks.

**Comment by csolisr** [comment] 2021-09-16 14:50
@JohnXLivingston I'll try to coinstall Prosody manually with the procedure you stated above, hopefully it doesn't cause dependencies to break.

**Comment by csolisr** [comment] 2021-09-16 15:00
Unfortunately, dependencies do break as the log states:
```
dpkg: about prosody_0.11.2-1+deb10u2_amd64.deb containing prosody:
  metronome conflicts with prosody
   prosody (version 0.11.2-1+deb10u2) will be installed.

dpkg: error processing file prosody_0.11.2-1+deb10u2_amd64.deb (--unpack):
  conflicting packages - prosody will not install
Errors were encountered while processing:
  prosody_0.11.2-1+deb10u2_amd64.deb 
```

**Comment by JohnXLivingston** [comment] 2021-09-16 15:18
Oh :(
That's annoying. 
You can install prosody manually: https://prosody.im/doc/installing_from_source
That's not ideal (not easy, and it will not update automatically), but I have no better idea for now.

**Comment by csolisr** [comment] 2021-09-16 15:51
Just installed it from source code, and added the prosody user and a systemd service manually. So far it seems to be working correctly according to the diagnosis tool, but the only issue I have so far is that in all the (non-live) videos I try, the chatroom doesn't open even though I explicitly asked it to be opened for all live and non-live videos.

```
Running hook action:video-watch.video.loaded of plugin livechat. plugins-manager.ts:93:14
[peertube-plugin-livechat] Checking if this video should have a chat... videowatch-client-plugin.js:1:2452
[peertube-plugin-livechat] This video has no webchat
```

Is that normal or do I still have to configure something else?

**Comment by JohnXLivingston** [comment] 2021-09-16 16:16
You don't have to add the prosody systemd service. You can remove it. Peertube will launch its own prosody process (I do so to not conflict with existing Prosody configuration... Prosody as global settings that can conflict between virtualhosts).

Have you selected the «prosody» chat mode?

Try to refresh your page. If it is not enought, try in a private tag (it could be a cache problem).

If it is still not working, try the diagnostic tool (the button in the settings page).
Or give me your instance url.

**Comment by goatmeal01** [comment] 2021-10-30 20:43
anyone have any luck getting yunohost metronome to work yet? I got it to work partially. I have peertube on example.tv and I made a yunohost subdomain chat.example.tv. the converse.js included with the plugin is connected and the subdomain's metronome settings are configured for anonymous login. I cannot access the chat room from a XMPP account outside of example.tv and I cannot get it to accept pictures being uploaded by anonymous users.

**Comment by JohnXLivingston** [comment] 2022-01-03 11:29
Hello. 
I'm still working on an easy solution to integrate the plugin in Yunohost. I did not find the perfect one for now.

In the meantime, you can try this: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/prosody.md#yunohost

I'm closing this issue. That does not mean I'm not working on a better approach.

**Closed by JohnXLivingston** 2022-01-03 11:29 UTC
Labels: Waiting answer
